package core

import (
	"context"
	"fmt"
	"strings"
	"time"

	"github.com/Podiom/Podiom/internal/adapter"
	"github.com/Podiom/Podiom/internal/store"
)

const (
	recentReplayMessages      = 12
	rollingSummaryMinMessages = 16
	rollingSummaryInterval    = 10
	summaryTimeout            = 45 * time.Second
)

func replayHistory(sess store.Session, history []store.Message) []store.Message {
	history = conversationMessages(history)
	if sess.RollingSummary == "" || len(history) <= recentReplayMessages {
		return history
	}
	recent := history[len(history)-recentReplayMessages:]
	compacted := make([]store.Message, 0, len(recent)+1)
	compacted = append(compacted, store.Message{
		Role:    store.RoleUser,
		Content: "Conversation summary so far (generated by Podiom for history replay):\n" + sess.RollingSummary,
	})
	compacted = append(compacted, recent...)
	return compacted
}

func (c *Core) refreshRollingSummaryBackground(sessionID string) {
	ctx, cancel := context.WithTimeout(context.Background(), summaryTimeout)
	defer cancel()
	_, _ = c.RefreshRollingSummary(ctx, sessionID)
}

// RefreshRollingSummary precomputes a compact summary of older session history
// so future profile/provider switches do not need to replay the full transcript.
func (c *Core) RefreshRollingSummary(ctx context.Context, sessionID string) (store.Session, error) {
	sess, err := c.store.GetSession(ctx, sessionID)
	if err != nil {
		return store.Session{}, err
	}
	history, err := c.store.ListMessages(ctx, sessionID)
	if err != nil {
		return store.Session{}, err
	}
	history = conversationMessages(history)
	if len(history) < rollingSummaryMinMessages {
		return sess, nil
	}
	if sess.RollingSummary != "" && len(history)%rollingSummaryInterval != 0 {
		return sess, nil
	}
	olderEnd := len(history) - recentReplayMessages
	if olderEnd <= 0 {
		return sess, nil
	}
	summary := c.generateSummaryWithModel(ctx, sess, history[:olderEnd])
	if strings.TrimSpace(summary) == "" {
		summary = deterministicSummary(history[:olderEnd])
	}
	return c.store.UpdateRollingSummary(ctx, sessionID, summary)
}

func (c *Core) generateSummaryWithModel(ctx context.Context, sess store.Session, older []store.Message) string {
	events, err := c.adapter.SendTurn(ctx, adapter.TurnRequest{
		SessionID: sess.ID + "-summary",
		Handle:    adapter.Handle{Provider: sess.Provider},
		Message: "Summarize the older portion of this Podiom session for future history replay. " +
			"Preserve durable user goals, important decisions, files mentioned, and unresolved tasks. " +
			"Return concise plain text only.\n\n" + transcript(older),
		Settings: adapter.TurnSettings{
			AgentName:         sess.AgentName,
			Profile:           sess.Profile,
			ProfileDir:        c.profileDir(sess.Provider, sess.Profile),
			Model:             sess.Model,
			Effort:            "low",
			PermissionMode:    sess.PermissionMode,
			WorkspaceDir:      c.AgentPaths(sess.AgentName).Workspace,
			PermissionTimeout: c.permissionTimeout(),
		},
	})
	if err != nil {
		return ""
	}
	var text strings.Builder
	for event := range events {
		switch event.Kind {
		case adapter.EventAssistantDelta:
			text.WriteString(event.Content)
		case adapter.EventAssistantMessage:
			text.Reset()
			text.WriteString(event.Content)
		}
	}
	return strings.TrimSpace(text.String())
}

// oneShotCompletion runs a single unattended turn against an agent's engine and
// returns the assistant's plain-text reply. It borrows the agent's
// provider/profile/model for working auth and uses low effort. It is used for
// short helper completions (e.g. drafting a project description) that are not
// tied to a durable session.
func (c *Core) oneShotCompletion(ctx context.Context, agent store.Agent, prompt string) string {
	return c.oneShotCompletionWithOptions(ctx, agent, prompt, oneShotOptions{})
}

type oneShotOptions struct {
	ExtraWorkspaceDirs []string
	Unattended         bool
	AllowedTools       []string
}

func (c *Core) oneShotCompletionWithOptions(ctx context.Context, agent store.Agent, prompt string, opts oneShotOptions) string {
	var relay adapter.PermissionRelay
	if opts.Unattended {
		relay = NewAllowListRelay(opts.AllowedTools)
	}
	events, err := c.adapter.SendTurn(ctx, adapter.TurnRequest{
		SessionID: "oneshot-" + agent.Name,
		Handle:    adapter.Handle{Provider: agent.Provider},
		Message:   prompt,
		Settings: adapter.TurnSettings{
			AgentName:          agent.Name,
			Profile:            agent.Profile,
			ProfileDir:         c.profileDir(agent.Provider, agent.Profile),
			Model:              agent.Model,
			Effort:             "low",
			PermissionMode:     agent.PermissionMode,
			WorkspaceDir:       c.AgentPaths(agent.Name).Workspace,
			ExtraWorkspaceDirs: opts.ExtraWorkspaceDirs,
			PermissionTurnID:   "oneshot-" + agent.Name,
			PermissionTimeout:  c.permissionTimeout(),
			Unattended:         opts.Unattended,
			AllowedTools:       opts.AllowedTools,
		},
		Relay: relay,
	})
	if err != nil {
		return ""
	}
	var text strings.Builder
	for event := range events {
		switch event.Kind {
		case adapter.EventAssistantDelta:
			text.WriteString(event.Content)
		case adapter.EventAssistantMessage:
			text.Reset()
			text.WriteString(event.Content)
		}
	}
	return strings.TrimSpace(text.String())
}

// oneShotCompletionErr is like oneShotCompletionWithOptions but surfaces failures
// instead of swallowing them: a transport error, a rate-limited turn, or an empty
// reply all return a non-nil error. The dream relies on this — a rate limit
// mid-dream must abort so the source sessions are not marked consolidated.
func (c *Core) oneShotCompletionErr(ctx context.Context, agent store.Agent, prompt string, opts oneShotOptions) (string, error) {
	var relay adapter.PermissionRelay
	if opts.Unattended {
		relay = NewAllowListRelay(opts.AllowedTools, c.log)
	}
	events, err := c.adapter.SendTurn(ctx, adapter.TurnRequest{
		SessionID: "oneshot-" + agent.Name,
		Handle:    adapter.Handle{Provider: agent.Provider},
		Message:   prompt,
		Settings: adapter.TurnSettings{
			AgentName:          agent.Name,
			Profile:            agent.Profile,
			ProfileDir:         c.profileDir(agent.Provider, agent.Profile),
			Model:              agent.Model,
			Effort:             "low",
			PermissionMode:     agent.PermissionMode,
			WorkspaceDir:       c.AgentPaths(agent.Name).Workspace,
			ExtraWorkspaceDirs: opts.ExtraWorkspaceDirs,
			PermissionTurnID:   "oneshot-" + agent.Name,
			PermissionTimeout:  c.permissionTimeout(),
			Unattended:         opts.Unattended,
			AllowedTools:       opts.AllowedTools,
		},
		Relay: relay,
	})
	if err != nil {
		return "", err
	}
	var (
		text        strings.Builder
		rateLimited bool
	)
	for event := range events {
		switch event.Kind {
		case adapter.EventAssistantDelta:
			text.WriteString(event.Content)
		case adapter.EventAssistantMessage:
			text.Reset()
			text.WriteString(event.Content)
		case adapter.EventRateLimited:
			rateLimited = true
		}
	}
	if err := ctx.Err(); err != nil {
		return "", err
	}
	if rateLimited {
		return "", fmt.Errorf("provider rate-limited the completion")
	}
	out := strings.TrimSpace(text.String())
	if out == "" {
		return "", fmt.Errorf("the model returned no output")
	}
	return out, nil
}

func deterministicSummary(history []store.Message) string {
	var b strings.Builder
	for _, msg := range history {
		if !isConversationMessage(msg) {
			continue
		}
		line := oneLine(msg.Content)
		if line == "" {
			continue
		}
		fmt.Fprintf(&b, "%s: %s\n", msg.Role, truncateRunes(line, 220))
	}
	return strings.TrimSpace(b.String())
}

func conversationMessages(history []store.Message) []store.Message {
	out := make([]store.Message, 0, len(history))
	for _, msg := range history {
		if isConversationMessage(msg) {
			out = append(out, msg)
		}
	}
	return out
}

func isConversationMessage(msg store.Message) bool {
	return msg.Kind == "" || msg.Kind == store.KindMessage
}
